# DEBUG CONFIGURATION - Quick tests to verify main_ours.py runs correctly
#
# DEBUG COST SUMMARY:
# ===================
# Total experiments: 3 runs (very fast)
# Total estimated time: ~6-12 minutes
# GPU memory required: ~5-7GB
# Storage needed: ~50-100MB total
# 
# PURPOSE: 
# - Verify main_ours.py runs without errors
# - Test all 3 repulsion types ('svgd', 'rlsd', 'wo')
# - Quick validation of pipeline
# - Fast iteration cycles for debugging
#
# USAGE:
# sbatch scripts/run_ours_debug.sh debug_quick_test

# DEBUG: Quick test - 3 repulsion types with minimal iterations
# COST ESTIMATE:
#   Total combinations: 3 × 1 = 3 runs (very fast!)
#   Time per run: ~2-4 min (50 iters)
#   Total time: ~6-12 minutes
#   GPU memory: ~5-7GB peak per run  
#   Storage: ~20-40MB per run (3 runs ≈ 60-120MB total)
#   Recommended SLURM: --time=00:30:00 --mem=16G --gres=gpu:1
debug_001:
  name: svgd_rlsd_wo
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd', 'rlsd', 'wo']  # Test all 3 methods quickly

  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    num_views: [8]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [1000]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    repulsion_tau: [0.5]
    iters: [200]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: false
    save_iid: false
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 2000     # Less frequent saves to reduce memory
    visualize_graph: false # save graph for debugging
    visualize_graph_interval: 100
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10           


debug_002:
  name: wo_metrics
  method: grid
  sweep_parameters:
    repulsion_type: ['wo', 'svgd', 'rlsd']  

  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    num_views: [8]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [1000]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    iters: [100]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: false
    save_iid: false
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 2000     # Less frequent saves to reduce memory
    visualize_graph: false # save graph for debugging
    visualize_graph_interval: 100
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 1     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10       
         # Less frequent for memory


debug_003:
  name: svgd_cosine_kernel
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd']  # Test svgd only
    repulsion_tau: [5.0]                   # 2.0~5.0 soft, 0.1~0.5 sharp
    grad_clip: [5.0]                       # 1.0~5.0 (clip gradient)
    lambda_sd: [0.1]                      # 0.01~0.1 (increase after being stable)
    lambda_repulsion: [1000]               # Single value
  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    num_views: [8]                         # Ultra minimal views for debugging
    kernel_type: ['cosine']
    repulsion_scale: [1.0]                   # scale for repulsive loss
    feature_layer: [6]                     # Single layer
    iters: [200]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: false
    save_iid: false
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 2000     # Less frequent saves to reduce memory
    visualize_graph: false # save graph for debugging
    visualize_graph_interval: 100
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10       
         # Less frequent for memory


debug_004:
  name: cosine_kernel_viz
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd', 'rlsd', 'wo']
    repulsion_tau: [5.0]                   # 2.0~5.0 soft, 0.1~0.5 sharp
    lambda_sd: [1]                      # 0.01~0.1 (increase after being stable)
    grad_clip: [5.0]                       # 1.0~5.0 (clip gradient)
    lambda_repulsion: [1000]               # Single value


  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [4]                     # Minimal particles for SVGD/RLSD (need >1)
    num_views: [8]                         # Ultra minimal views for debugging
    repulsion_scale: [1.0]                   # scale for repulsive loss
    feature_layer: [11]                     # Single layer
    kernel_type: ['cosine']
    iters: [1200]                              
    
  settings:
    visualize: true
    save_iid: false
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 2000     # Less frequent saves to reduce memory
    visualize_graph: false # save graph for debugging
    visualize_graph_interval: 100
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10       
         # Less frequent for memory



debug_005:
  name: rbf_kernel_viz
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd', 'rlsd', 'wo']
    repulsion_tau: [5.0]                   # 2.0~5.0 soft, 0.1~0.5 sharp
    lambda_sd: [1]                      # 0.01~0.1 (increase after being stable)
    grad_clip: [5.0]                       # 1.0~5.0 (clip gradient)
    lambda_repulsion: [1000]               # Single value


  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [4]                     # Minimal particles for SVGD/RLSD (need >1)
    num_views: [8]                         # Ultra minimal views for debugging
    repulsion_scale: [1.0]                   # scale for repulsive loss
    feature_layer: [11]                     # Single layer
    kernel_type: ['rbf']
    iters: [1200]                              
    
  settings:
    visualize: true
    save_iid: false
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 2000     # Less frequent saves to reduce memory
    visualize_graph: false # save graph for debugging
    visualize_graph_interval: 100
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10       
         # Less frequent for memory


debug_006:
  name: rbf_cosine_kernel_viz
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd', 'rlsd', 'wo']
    repulsion_tau: [5.0]                   # 2.0~5.0 soft, 0.1~0.5 sharp
    lambda_sd: [1]                      # 0.01~0.1 (increase after being stable)
    grad_clip: [5.0]                       # 1.0~5.0 (clip gradient)
    lambda_repulsion: [1000]               # Single value


  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [4]                     # Minimal particles for SVGD/RLSD (need >1)
    num_views: [8]                         # Ultra minimal views for debugging
    repulsion_scale: [1.0]                   # scale for repulsive loss
    feature_layer: [11]                     # Single layer
    kernel_type: ['rbf', 'cosine']
    iters: [1200]                              
    
  settings:
    visualize: true
    save_iid: false
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 2000     # Less frequent saves to reduce memory
    visualize_graph: false # save graph for debugging
    visualize_graph_interval: 100
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10       
    # Less frequent for memory

debug_007:
  name: svgd_rlsd_wo_graph_viz
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd', 'rlsd', 'wo']  # Test all 3 methods quickly

  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [4]                     # Minimal particles for SVGD/RLSD (need >1)
    num_views: [8]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [700]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    iters: [500]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: true
    save_iid: true
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 1000     # Less frequent saves to reduce memory
    visualize_graph: true # save graph for debugging
    visualize_graph_interval: 100
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 50     # Less frequent metrics
    losses_interval: 25                    # Less frequent for memory
    efficiency_interval: 25         

debug_008:
  name: save_features_from_different_layers
  method: grid
  sweep_parameters:
    feature_layer: [3, 6, 11]
  
  fixed_parameters:
    seed: [42]
    prompts: ["a photo of a hamburger"]
    repulsion_type: ['svgd', 'rlsd', 'wo']
    lambda_repulsion: [700]
    num_particles: [4]
    num_views: [8]
    repulsion_tau: [0]
    lambda_sd: [1.0]
    kernel_type: ['rbf']
    iters: [500]

  settings:
    visualize: true
    save_iid: false
    save_rep_features: true # save features from different layers
    save_rep_features_interval: 50
    save_rendered_images_interval: 100
    save_multi_viewpoints_interval: 100
    metrics: true
    quantitative_metrics_interval: 50
    losses_interval: 50
    efficiency_interval: 50
# ==================
# ============================================================================
# DEBUG CONFIGURATION COMPLETE
# ============================================================================
# This debug config only contains one experiment (debug_quick_test) with:
# - 3 runs total (svgd, rlsd, wo)
# - 50 iterations each (~2-4 min per run)
# - Minimal resources for quick validation
# - Frequent saves/metrics for debugging
#
# TO RUN: sbatch scripts/run_ours_debug.sh debug_quick_test
# RESULTS: Check logs/debug_001/ for the 3 test runs
# ============================================================================
