# DEBUG CONFIGURATION - Quick tests to verify main_ours.py runs correctly
#
# DEBUG COST SUMMARY:
# ===================
# Total experiments: 3 runs (very fast)
# Total estimated time: ~6-12 minutes
# GPU memory required: ~5-7GB
# Storage needed: ~50-100MB total
# 
# PURPOSE: 
# - Verify main_ours.py runs without errors
# - Test all 3 repulsion types ('svgd', 'rlsd', 'wo')
# - Quick validation of pipeline
# - Fast iteration cycles for debugging
#
# USAGE:
# sbatch scripts/run_ours_debug.sh debug_quick_test

# DEBUG: Quick test - 3 repulsion types with minimal iterations
# COST ESTIMATE:
#   Total combinations: 3 × 1 = 3 runs (very fast!)
#   Time per run: ~2-4 min (50 iters)
#   Total time: ~6-12 minutes
#   GPU memory: ~5-7GB peak per run  
#   Storage: ~20-40MB per run (3 runs ≈ 60-120MB total)
#   Recommended SLURM: --time=00:30:00 --mem=16G --gres=gpu:1
debug_001:
  name: all_3_methods
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd', 'rlsd', 'wo']  # Test all 3 methods quickly

  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    multi_view_type: ['average_views']
    num_views: [4]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [100]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    iters: [100]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: true
    save_iid: true
    save_rendered_images_interval: 50      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 300     # Less frequent saves to reduce memory
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10           

debug_002:
  name: svgd
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd']  # Test svgd only
  
  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    multi_view_type: ['average_views']
    num_views: [4]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [100]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    iters: [100]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: true
    save_iid: true
    save_rendered_images_interval: 50      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 300     # Less frequent saves to reduce memory
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10           

debug_003:
  name: rlsd
  method: grid
  sweep_parameters:
    repulsion_type: ['rlsd']  # Test rlsd only
  
  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    multi_view_type: ['average_views']
    num_views: [4]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [100]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    iters: [100]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: true
    save_iid: true
    save_rendered_images_interval: 50      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 300     # Less frequent saves to reduce memory
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 10     # Less frequent metrics
    losses_interval: 10                    # Less frequent for memory
    efficiency_interval: 10               # Less frequent for memory


debug_004:
  name: svgd_rlsd
  method: grid
  sweep_parameters:
    repulsion_type: ['svgd', 'rlsd']  # Test rlsd only

  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    multi_view_type: ['average_views']
    num_views: [4]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [1.0]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    iters: [300]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: true
    save_iid: true
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 300     # Less frequent saves to reduce memory
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 50     # Less frequent metrics
    losses_interval: 25                    # Less frequent for memory
    efficiency_interval: 25               # Less frequent for memory


debug_005:
  name: wo
  method: grid
  sweep_parameters:
    repulsion_type: ['wo']  # Test rlsd only

  fixed_parameters:
    seed: [42]                             # Single seed for speed
    prompts: ["a photo of a hamburger"]    # Simple prompt
    num_particles: [2]                     # Minimal particles for SVGD/RLSD (need >1)
    multi_view_type: ['average_views']
    num_views: [4]                         # Ultra minimal views for debugging
    repulsion_tau: [0]
    lambda_sd: [1.0]
    lambda_repulsion: [1.0]                # Single value
    feature_layer: [6]                     # Single layer
    kernel_type: ['rbf']
    iters: [300]                                # Very short for debugging (~2-4 min per run)

  settings:
    visualize: true
    save_iid: true
    save_rendered_images_interval: 100      # Less frequent saves to reduce memory
    save_multi_viewpoints_interval: 300     # Less frequent saves to reduce memory
    metrics: true                         # Enable metrics to save memory
    quantitative_metrics_interval: 50     # Less frequent metrics
    losses_interval: 25                    # Less frequent for memory
    efficiency_interval: 25               # Less frequent for memory

# ==================
# ============================================================================
# DEBUG CONFIGURATION COMPLETE
# ============================================================================
# This debug config only contains one experiment (debug_quick_test) with:
# - 3 runs total (svgd, rlsd, wo)
# - 50 iterations each (~2-4 min per run)
# - Minimal resources for quick validation
# - Frequent saves/metrics for debugging
#
# TO RUN: sbatch scripts/run_ours_debug.sh debug_quick_test
# RESULTS: Check logs/debug_001/ for the 3 test runs
# ============================================================================
